apiVersion: v1
kind: PersistentVolume
metadata:
    name: calibre-books
    namespace: calibre
spec:
    volumeMode: Filesystem
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: local-storage
    local:
        path: /opt/data/calibre/books/
