apiVersion: v1
kind: PersistentVolume
metadata:
    name: calibre-books
    namespace: calibre
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: local-storage
    localPath:
        path: /var/data/calibre/books/
